background/background.js
content/pick-images.js
manifest.json

Fixes #4.
The command can be accessed from context menu.

Add: pick images from tabs to the right

---

css/common.css
lib/pref.js
options/options.css
options/options.html
picker/picker.css
picker/picker.html

Add: text input history, use position: fixed for toolbar

---

.editorconfig
_locales/en/messages.json
content/dragndrop.js
lib/pref.js
options/options.html

Add: blacklist option

---

_locales/en/messages.json
content/dragndrop.js
lib/pref.js
options/options.html

Add: downloadButtonPosition options

---

content/dragndrop.js
content/pick-images.js

Fix: make download single image use getImageSrc

---

.editorconfig
_locales/en/messages.json
background/background.js
lib/pref.js
options/options.html

Add: option to handle filename conflict

---

README.md
content/dragndrop.js
options/options.html

Add: subdomain syntax in blacklist

---

README.md
background/background.js

Add: date and dateString variables

---

background/background.js

Fix: close tab feature doesn't obey exclude current option

---

background/background.js

Fix: ignore download cancel error

---

extension/_locales/en/messages.json
extension/lib/pref.js
extension/options/options.html
extension/picker/picker.css
extension/picker/picker.js

Add: display image size under thumbnails.

---

extension/picker/picker.css
extension/picker/picker.js

Fix: switch back to checkbox

---

extension/background/background.js

Fix: don't throw if pickImages is undefined

---

extension/_locales/en/messages.json
extension/content/dragndrop.js
extension/lib/pref.js
extension/options/options.html

Add: downloadButtonSize option

---

extension/background/background.js

Fix: escape leading/trailing spaces. Fallback to pageUrl when pageTitle is empty

---

extension/background/background.js

Fix: remove zero width spaces

---

extension/_locales/en/messages.json
extension/lib/pref.js
extension/options/options.html
extension/picker/picker.js

Add: previewMaxHeightUpperBound option

---

extension/content/dragndrop.js

Add: support srcset from img/source

---

extension/_locales/en/messages.json
extension/options/options.html

Add: filename pattern and close tabs options in batch download to the options page

---

extension/picker/picker.css
extension/picker/picker.js

Add: a cover image that is load from the real URL

---

extension/picker/picker.js

Add: validate image URL

---

extension/content/dragndrop.js

Add: cancel drop when other buttons are pressed

---

extension/background/background.js
extension/content/content.js
extension/lib/fetch-image.js
extension/manifest.json
extension/picker/picker.js

Add: fallback to background fetch in Chrome, fix mixed content error

---

extension/content/content.js
extension/lib/fetch.js

Add: fetch fallback in Chrome

---

extension/content/dragndrop.js

Add: animation for the download button

---

extension/_locales/en/messages.json
extension/lib/pref.js
extension/options/options.html
extension/picker/picker.js

Add: selectByDefault option

---

extension/content/dragndrop.js

Fix: download button is broken in waterfox

---

README.md
extension/_locales/en/messages.json
extension/background/background.js
extension/lib/pref.js
extension/options/options.html

Add: escapeZWJ option

---

extension/content/content.js
extension/content/dragndrop.js
extension/content/image-util.js
extension/manifest.json

Add: treat input[type=image] as images

---

extension/content/image-util.js

Fix: make sure to use absolute URL

---

extension/_locales/en/messages.json
extension/content/content.js
extension/content/image-util.js
extension/lib/pref.js
extension/options/options.html

Add: detect image URLs from link option

---

extension/background/background.js

Fix: escape filename according to Firefox's sanitize method

---

extension/_locales/en/messages.json
extension/css/common.css
extension/picker/picker.css
extension/picker/picker.html
extension/picker/picker.js

Add: responsive picker

---

src/background.js
src/static/manifest.json

Add: keyboard shortcuts

---

src/lib/dragndrop.js

Fix: click/double click download is broken

---

src/lib/dragndrop.js
src/lib/fetch.js

Fix: ignore invisible images when drag-n-drop

---

src/dialog.js
src/lib/custom-css.js
src/lib/fetch.js
src/lib/pref.js
src/options.js
src/picker.js
src/static/_locales/en/messages.json

Add: custom css, only use content fetch as fallback

---

src/picker.js

Revert: use real URL for thumbnails

---

src/lib/tab.js

Fix: use retry logic when creating tabs with opener

---

src/background.js

Add: pageName variable

---

.cjsescache
package-lock.json
package.json
src/background.js
src/lib/string-template.js
src/picker.js

Change: switch to espression

---

.github/workflows/build.yml
.github/workflows/release.yml
package-lock.json
package.json
src/background.js
src/lib/string-template.js
src/options.js

Change: always use the expression compiler

---

src/background.js
src/options.js
src/static/_locales/en/messages.json
src/static/manifest.json

Change: pick from current -> pick from highlighted

---

package-lock.json
package.json
rollup.config.js
src/background.js
src/lib/downloader.js
web-ext-config.js

Add: support referer in downloads api

---

src/picker.js

Change: only load 3 images at once in the same origin

---

.cjsescache
package-lock.json
package.json
rollup.config.js
src/background.js
src/lib/expand-env.mjs

Fix: switch to image-extensions, recognize webp

---

src/background.js
src/lib/expand-env.mjs
src/picker.js

Add: preview filename

---

src/lib/progress.js
src/static/_locales/en/messages.json
src/static/css/progress.css

Add: show progress on the title, don't hide the progress if there is an error

---

src/background.js

Fix: open tab next to the current in Chrome

---

src/background.js
src/lib/downloader.js
src/lib/pref.js
src/options.js
src/static/_locales/en/messages.json

Add: clear download history option

---

.travis.yml
src/background.js

Fix: release memory after getting blob

---

src/lib/dragndrop.js

Fix: button animation is never canceled

---

src/lib/dragndrop.js
src/lib/image-util.js

Fix: try to match the max source in picture element

---

src/lib/expand-env.mjs

Fix: parse more image extension

---

src/background.js

Fix: dateString is broken in single download

---

package-lock.json
package.json
src/lib/image-util.js

Fix: srcset parsing issue

---

src/lib/tab.js
src/picker.js

Add: open image in new tab via middle click

---

README.md
src/background.js
src/lib/fetch-delay.js
src/lib/image-cache.js
src/lib/pref.js
src/options.js
src/static/_locales/en/messages.json

Add: fetchDelay option

---

.eslintrc.json
.gitignore
package.json
src/background.js
src/lib/image-util.js

Fix: do not parse empty srcset

---

src/content.js

Fix: compare image info before removing dups

---

src/background.js
src/content.js
src/lib/image-util.js
src/lib/tab-monitor.js
src/picker.js
src/static/_locales/en/messages.json
src/static/manifest.json

Fixes #358.
We have to extract more information to locate the image, including
1. tag name
2. property name
3. property value (before url transform)
4. tab id
5. frame id
or is it possible to ref the image without leaking memory?

WIP: view the source element

---

README.md
src/lib/fetch-delay.js

Add: glob in fetch delay
